# ──────────────────────────────────────────────────────────────────────────────
# CUSTOM (MDS)
# ──────────────────────────────────────────────────────────────────────────────

notify = ["zsh", "/Users/devin/.codex/notify.sh"]
model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
[tui]
notifications = false

[shell_environment_policy.set]
CODEX_NOTIFY_SENDER_BUNDLE_ID = "none"

# ──────────────────────────────────────────────────────────────────────────────
# CODEX DEFAULT SETTINGS
# ──────────────────────────────────────────────────────────────────────────────

[notice]
hide_gpt-5.1-codex-max_migration_prompt = true
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[features]
unified_exec = true
shell_snapshot = true
collab = true
steer = true


# ──────────────────────────────────────────────────────────────────────────────
# MCP SERVERS
# ──────────────────────────────────────────────────────────────────────────────

[mcp_servers.chrome_devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--browserUrl", "http://127.0.0.1:9222", "--logFile", "/Users/devin/repos/projects/serp-video-downloader/tmp/chrome-devtools-mcp.log"]
enabled = true

[mcp_servers.eslint]
command = "npx"
args = ["@eslint/mcp@latest"]
enabled = true

[mcp_servers.next_devtools]
command = "npx"
args = ["-y", "next-devtools-mcp@latest"]
enabled = true

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--extension"]
enabled = true

[mcp_servers.upstash_context7]
command = "npx"
args = ["mcp-remote", "https://mcp.context7.com/mcp", "--header", "Authorization: Bearer ctx7sk-7ebac37c-6f0f-41d4-abb2-3dd6e49bb9cf"]
enabled = true

